### ISSUE TITLE
[BUG]: The Fuse client cannot manipulate files in the mounted HDFS/s3 directory.

### ISSUE THREAD

**Issue by jlon** [CurvineIO/curvine#402]
I used the command shown below to mount s3 to /mnt/s3 in the curvine path.
```
./dist/bin/cv mount s3://flink/user /mnt/s3  -c s3.endpoint_url=http://xxxx-access-test.wanyol.com   -c s3.region_name=xxxx   -c s3.credentials.access=xxxx  -c s3.credentials.secret=xxxxxxx
```
Next, as the root user, I started the mount point using the following command: `./build/dist/bin/curvine-fuse.sh start`. Then, I went to the mount point directory `/curvine-fuse/mnt/s3` and tried to manipulate files using the following command, but it failed.
```
root@localhost:/curvine-fuse/mnt/s3# echo "1" >> test.log
-bash: test.log: Input/output error
root@localhost:/curvine-fuse/mnt/s3# touch test.log
touch: setting times of 'test.log': No such file or directory
```

**Comment by szbr9486** [comment]
Thank you for your feedback. We have fixed this issue. If you encounter any other problems while using it in the future, please let us know anytime. Thank you again for your patience and support.

**Comment by 201341** [comment]
@szbr9486  this issue hasn't been fixed, And still can't append in ufs.

**Comment by jlon** [comment]
Resolved by #431 and #687. UFS-backed file creation was fixed, and the later write path handles UFS-only append through the normal open-with-options flow; #687 includes append regression coverage.
